version: '3'

services:
  cache:
    container_name: temp_cache
    image: redis:alpine
    restart: always
  app:
    image: XXXXXX:latest
    container_name: temp_app 
    depends_on:
      - redis
    restart: always
    networks:
      - nextcloud_network
    ports:
      - "30080:80"
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./env_files/XXXXXX_auth.env
    volumes:
      - type: bind
        source: ./volumes/nextcloud
        target: /var/www/html

volumes:
  nextcloud_postgres:

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
