version: '3'

services:
  cache:
    container_name: XXX_cache
    image: redis:alpine
    networks:
      - default
    restart: always
  app:
    image: XXX:latest
    container_name: XXX_app 
    depends_on:
      - redis
    restart: always
    networks:
      - default
    ports:
      - "30080:80"
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./env_files/XXX_auth.env
    volumes:
      - type: bind
        source: ./volumes/xxx
        target: /var/www/html

volumes:
  XXX:

networks:
  default:
    name: XXX_network
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
