version: '3'

services:
  db:
  # container_name: 
    image: mongo:6.0
    restart: always
    networks:
      - mongo_network
    ports:
      - "37017:27017"
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./envs/mongodb_auth.env
    # volumes:
    #   - type: bind
    #     source: ./volumes/nextcloud 
    #     target: /var/www/html
  app:
    container_name: mongo_express
    image: mongo-express:0.54
    depends_on:
      - db
    restart: always
    networks:
      - mongo_network
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./envs/mongo-express.env

networks:
  mongo_network:
