version: '3'

services:
  app:
    container_name: mongo_express
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - redis
    restart: always
    networks:
      - mongo_network
    ports:
      - "8081:48081"
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./env_files/mongo-express.env
    # volumes:
    #   - type: bind
    #     source: ./volumes/mongo_express 
    #     target: /var/www/html


# volumes:
#   mongo:

networks:
  mongo:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.9.0/24

      