version: '3'

services:
  db:
    image: postgres:14.4
    restart: always
    # networks:
    #   - nextcloud_network
    #   - postgres_network
    ports:
      - "30081:5432"
    env_file:
      - ./envs/db_auth.env
    # environment:
    #   - POSTGRES_DB=nextcloud
    volumes:
      # DBデータ永続用
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:25.0.1
    depends_on:
      - db
      - redis
    restart: always
    # networks:
    #   - nextcloud_network
    ports:
      - "31683:80"
    env_file:
      - ./envs/db_auth.env
      - ./envs/nextcloud.env
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    volumes:
      - type: bind
        source: ./volumes/nextcloud
        target: /var/www/html
      # container に login した時用の bash alias など。
      - type: bind
        source: /mnt/lvm-public
        target: /data
        volume:
          nocopy: false

volumes:
  nextcloud_postgres:


networks:
  nextcloud_network:
  postgres_network:
