version: '3.9'

services:
  db:
    image: postgres:15.3
    container_name: nextcloud_db
    restart: always
    networks:
      - default
      - pgadmin
    ports:
      - "30081:5432"
    env_file:
      - ./envs/db_auth.env
    # environment:
    #   - POSTGRES_DB=nextcloud
    volumes:
      # DBデータ永続用
      - type: bind
        source: ./volumes/postgres
        target: /var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: nextcloud_cache
    restart: always
    networks:
      - default

  app:
    image: nextcloud:25.0.7-apache
    container_name: nextcloud_app
    depends_on:
      - db
      - redis
    restart: always
    # user: "www-data:www-data"
    networks:
      - default
      - nextcloud
    ports:
      - "31683:80"
    env_file:
      - ./envs/db_auth.env
      - ./envs/nextcloud.env
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    volumes:
      # - type: bind
      #   source: ./volumes/nextcloud
      #   target: /var/www/html
      # - type: bind
      #   source: /mnt/lvm-public/nextcloud/var
      #   target: /var
      #   volume:
      #     nocopy: false
      - type: bind
        source: ./volumes/nextcloud/nextcloud/data
        target: /var/www/data
      # - type: bind
      #   source: /mnt/lvm-public/nextcloud/php
      #   target: /usr/local/etc/php
      #   volume:
      #     nocopy: false

# volumes:
#   app_data:
#     name: nextcloud_app_data_volume
#     driver: local
#     driver_opts:
#       type: none
#       device: /mnt/lvm-public/nextcloud/data
#       o: bind
#   postgres_volume:
#     name: nextcloud_postgres_volume


networks:
  default:
    name: nextcloud_network_default
  nextcloud:
    name: nextcloud_network_external
    external: true
  pgadmin:
    name: pgadmin_network_external
    external: true
