version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    # depends_on:
    restart: always
    networks:
      - postgres_network
    ports:
      - "30512:5432"
      - "50122:22"
    # environment:
    env_file:
      - ./envs/postgres_auth.env
    volumes:
      # DBデータ永続用
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

      # 初回起動時実行用スクリプトの保存場所
      - type: bind
        source: ./volumes/postgres_init
        target: /docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4:6.12
    restart: always
    depends_on:
      - postgres
    networks:
      - postgres_network
    environment:
      - PGADMIN_LISTEN_PORT=5678
    env_file:
      - ./envs/pgadmin_auth.env
    ports:
      - "30507:5678"
    volumes:
      # 接続先情報の永続化
      - type: bind
        source: ./volumes/pgadmin/servers.json
        target: /pgadmin4/servers.json

volumes:
  postgres_data:


networks:
  postgres_network:
