version: '3'

services:
  app:
    # container_name: 
    image: nginx:latest
    restart: always
    networks:
      - nginx
    # network_mode: "host"
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
    # env_file:
    #   - ./env_files/XXXXXX_auth.env
    volumes:
      - type: bind
        source: ./volumes/nginx/conf.d
        target: /etc/nginx/conf.d


# volumes:
#   nextcloud_postgres:

networks:
  nginx:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

      