version: '3'

services:
  app:
    image: wordpress:6.1.1-php8.2
    container_name: wordpress 
    restart: always
    networks:
      - nextcloud_network
    ports:
      - "30716:80"
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./env_files/XXXXXX_auth.env
    volumes:
      - type: bind
        source: ./volumes/nextcloud
        target: /var/www/html

volumes:
  nextcloud_postgres:

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
