version: '3'

services:
  redis:
    # いらない気がする 
    # container_name: text
    image: redis:alpine
    restart: always
  app:
    # container_name: 
    image: XXXXXX:latest
    depends_on:
      - redis
    restart: always
    networks:
      - nextcloud_network
    ports:
      - "30080:80"
    environment:
      - REDIS_HOST=redis
    env_file:
      - ./env_files/XXXXXX_auth.env
    volumes:
      - type: bind
        source: ./volumes/nextcloud 
        target: /var/www/html


volumes:
  nextcloud_postgres:

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24

      